### ISSUE TITLE
最后一步转换pdf的时候报错

### ISSUE THREAD

**Issue by 5536086** [kangdongdong/wenquanbook#1]
Traceback (most recent call last):
  File "main.py", line 135, in <module>
    change_pdf.run(id)
  File "E:\wenquanbook-master\change_pdf.py", line 20, in run
    book = wqxtDownloader(bid);
  File "E:\wenquanbook-master\wqxtDownloader.py", line 37, in __init__
    self.catatree = self.getCatatree();
  File "E:\wenquanbook-master\wqxtDownloader.py", line 95, in getCatatree
    cataTree = json.loads( data );
  File "D:\Python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "D:\Python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Python37\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 16381 (char 16380)

**Comment by kiedeng** [comment]
是不是json串漏复制了一些？

**Comment by 5536086** [comment]
发现问题了，是cmd有字符串长度限制，超长了，所以最后的json不完整了，这个如何解决哦

**Comment by kiedeng** [comment]
我用的pycharm运行的，你要不使用IDE运行？或者你改改代码，把这些信息放文件里，我刚开始是把这些复制的json串放文件里的，里面还有这些操作的注释

**Comment by 5536086** [comment]
看来只能用IDE工具了。对了，这个下载的图片是不是小图呀？

**Comment by kiedeng** [comment]
不是的

**Comment by kangdongdong** [comment]
图片在books/IMG/里，你可以看看

**Comment by 5536086** [comment]
嗯，我先去转pdf看看效果吧，

**Comment by kiedeng** [comment]
图片在books/IMG/里，你可以看看

**Comment by 5536086** [comment]
好了，嘿嘿，谢谢啊，这软件下载速度挺快，但是有时候会卡主，需要重启

**Comment by kiedeng** [comment]
可以适当调调线程数目；请求加一下timeout；

**Comment by 5536086** [comment]
主要是不会，哈哈，先这样用吧

**Comment by 5536086** [comment]
ID：3184599最后合成PDF报错：
Traceback (most recent call last):
  File "E:/wenquanbook-master/main.py", line 135, in <module>
    change_pdf.run(id)
  File "E:\wenquanbook-master\change_pdf.py", line 21, in run
    book.start();
  File "E:\wenquanbook-master\wqxtDownloader.py", line 198, in start
    pdf.generatePDF();
  File "E:\wenquanbook-master\wqxtPDF.py", line 64, in generatePDF
    self.addBookMarks();
  File "E:\wenquanbook-master\wqxtPDF.py", line 79, in addBookMarks
    doc.setToC(toc);
  File "D:\Python37\lib\site-packages\fitz\utils.py", line 852, in setToC
    raise ValueError("bad hierarchy level in row %i" % (i + 1))
ValueError: bad hierarchy level in row 155

**Comment by kiedeng** [comment]
就这一本吧？应该是下载的时候有个别的图片下载出错了，你用文件资源管理器在books/IMG/(本书id)的目录看一下，找一下打不开的文件删了就行了；
或者你直接删了books/IMG/(本书id)的目录，重新下载

**Comment by 5536086** [comment]
额，我看所有图片都有大小的，如果打不开就是0kb的。我试试吧，这个问题蛋疼了

**Comment by kiedeng** [comment]
用文件资源管理器打开的时候，如果能打开，它会显示小小的图标，很容易锁定的

**Comment by 5536086** [comment]
我检查了下，都有缩略图的，并且图片张数也对，好奇怪，我删除重新下载一次试试吧

**Comment by kiedeng** [comment]
嗯

**Comment by 5536086** [comment]
还是不行，又报别的错误：
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\img2pdf.py", line 1165, in read_images
    imgdata = Image.open(im)
  File "D:\Python37\lib\site-packages\PIL\Image.py", line 2862, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001494EC8F4C8>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:/wenquanbook-master/main.py", line 135, in <module>
    change_pdf.run(id)
  File "E:\wenquanbook-master\change_pdf.py", line 21, in run
    book.start();
  File "E:\wenquanbook-master\wqxtDownloader.py", line 198, in start
    pdf.generatePDF();
  File "E:\wenquanbook-master\wqxtPDF.py", line 59, in generatePDF
    pfn_bytes = img2pdf.convert( lists, with_pdfrw=False );
  File "D:\Python37\lib\site-packages\img2pdf.py", line 1829, in convert
    ) in read_images(rawdata, kwargs["colorspace"], kwargs["first_frame_only"]):
  File "D:\Python37\lib\site-packages\img2pdf.py", line 1171, in read_images
    "PIL: error reading image: %s" % e
img2pdf.ImageOpenError: cannot read input image (not jpeg2000). PIL: error reading image: cannot identify image file <_io.BytesIO object at 0x000001494EC8F4C8>

**Comment by 5536086** [comment]
我放弃了，这本书有毒

**Comment by kiedeng** [comment]
你再仔细看看缩略图，是不是存在不对的图，应该是有个图格式不对

**Comment by 5536086** [comment]
都改了，都仔细看了呢，没啥问题

**Comment by kiedeng** [comment]
嗯，行吧，
